import {
  LayoutGrid,
  MessageCircle,
  LockKeyhole,
  Mail,
  CreditCard,
  User,
  KeyRound,
  PieChart,
  Users,
  Hash,
  ChartNoAxesCombined,
  Users2,
  FileText,
  ShieldUser,
  Home,
  Settings2,
  Wallet,
  ChartBar,
} from "lucide-react";
import { JSX } from "react";

export const iconMap: Record<string, JSX.Element> = {
  GridIcon: <LayoutGrid size={18} />,
  MessageCircle: <MessageCircle size={18} />,
  LockKeyhole: <LockKeyhole size={18} />,
  MailIcon: <Mail size={18} />,
  CreditCard: <CreditCard size={18} />,
  User: <User size={18} />,
  KeyRound: <KeyRound size={18} />,
  PieChart: <PieChart size={18} />,
  Users: <Users size={18} />,
  Hash: <Hash size={18} />,
  ChartNoAxesCombined: <ChartNoAxesCombined size={18} />,
  Users2: <Users2 size={18} />,
  FileText: <FileText size={18} />,
  ShieldUser: <ShieldUser size={18} />,
  Home: <Home size={18} />,
  Settings2: <Settings2 size={18} />,
  Wallet: <Wallet size={18} />,
  ChartBar: <ChartBar size={18} />,
};
